services:
  mysql_db_thymeleaf:
    image: mariadb:latest
    ports:
      - "3307:3306"
    container_name: mysql_db_thymeleaf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: costumers_db #Database name
      MYSQL_USER: admin #Database user
      MYSQL_PASSWORD: admin #Database password
    volumes:
      - mysql_data:/var/lib/mysqlthymeleaf
    restart:
      always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
  mysql-db-inventory:
    image: mariadb:10.6
    container_name: mysql-db-inventory
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: inventory-db
      MYSQL_USER: elmehdi
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    # a but de gérer dépendance entre les conteneur
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_HOST: mysql-db-inventory
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: "exit 0"
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: elmehdi@gmail.ma
      PGADMIN_DEFAULT_PASSWORD: azer
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-service:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: 1234
      #KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      #KC_HTTP_ENABLED: "true"
      #KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      postgres-service:
          condition: service_healthy

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - '2222:2222'
    expose:
      - '2222'
    restart: always
    depends_on:
      mysql-db-inventory:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://mysql-db-inventory:3306/inventory-db
      - JWT_ISSUER_URI=http://localhost:8080/realms/sdia-realm
      - JWT_JWK_SET_URI=http://keycloak:8080/realms/sdia-realm/protocol/openid-connect/certs

  customer-front-thymeleaf-app:
    build: ./customer-front-thymeleaf-app
    container_name: customer-front-thymeleaf-app
    ports:
      - '1111:1111'
    expose:
      - '1111'
    restart: always
    depends_on:
      - keycloak
    environment:
      - DB_URL=jdbc:mysql://mysql_db_thymeleaf:3306/costumers_db
      - KEYCLOAK_REDIRECT_URI=http://localhost:1111/login/oauth2/code/sdia-customers-app
      #- KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/sdia-realm
      - KEYCLOAK_AUTH=http://localhost:8080/realms/sdia-realm/protocol/openid-connect/auth
      # Pb !!
      - KEYCLOAK_AUTH_TOKEN=http://keycloak:8080/realms/sdia-realm/protocol/openid-connect/token
      - JWT_JWK_SET_URI=http://keycloak:8080/realms/sdia-realm/protocol/openid-connect/certs
      - INVENTORY_SERVICE_BASE_URI=http://inventory-service:2222


      #- DB_URL=jdbc:mysql://mysql_db_thymeleaf:3306/costumers_db
      #- KEYCLOAK_AUTH_TOKEN=http://localhost:8080/realms/auth_apps/protocol/openid-connect/token
      #- ISSUER_URI=http://localhost:8080/realms/auth_apps

  customer-front-angular-app:
    build: ./customer-front-angular-app
    container_name: customer-front-angular-app
    ports:
      - '8085:80'
    expose:
      - '8085'
    restart: always

volumes:
  mysql_data:
  postgres_data:
  pgadmin_data: